### ISSUE TITLE
Add   surveyResponseID to the response table/endpoint

### ISSUE THREAD

**Issue by CTAJavier** [hmis-api/survey-service-api#1]
Currently there is an endpoint to track survey responses and an endpoint to track question responses, however there is nothing that allows us to link all the separate question responses to the survey response, in essence there is no way to check if our survey response set uploaded correctly. having that surveyResponseId allows us to compare all the questions submitted for that response id to the one we are storing in the MongoDB,

Thanks

**Comment by eric-jahn** [comment]
@suryayadavalli: let's discuss this during our call today.  The requirement is in line with initial requirements, so I'm just wondering whether there isn't already a way to do this.

**Comment by eric-jahn** [comment]
@CTAJavier, could you help us come up with the specific use case for this?  

We discussed this during our call today, and Surya clarified a little more.  The current APIs support survey response retrieval, both as a whole for a VI-SPDAT survey submission to be scored, and subsets of that submission by time frame of actual data entry.  But we need to verify this meets your needs.

We started a use case consisting of a user, John Smith, who completes half the sections of a VI-SPDAT-IND assessment survey on Oct 1, 2016.  The first 20 of 50 (a made up #) total questions he responds to between 9am and 9:30am pdt.  The second and final set of 30 questions is responded to in a second login session between 11:00am and 11:30am pdt.  At 11:30am pdt, the VI-SPDAT-IND assessment is submitted by John Smith, and it is scored. 

Am I correct in saying that you want to be able to retrieve the first set of 20 responses as a set? Alternatively, you may want to retrieve the second set of 30 questions independently from the first set?  So, it would be response retrieval based on user sessions?  Thanks for your clarifications.

**Comment by CTAJavier** [comment]
So, here is what i see right now, in the /clients/{clientid}/surveys/{surveyid}/responses, there are response IDs genereated for each of the responses posted, but not a unifying ID to tie all of the responses together. the scenario is more if the client takes the same survey multiple times how do we know which response IDs go together. currently the survey ID is the ID created in the API that stores the questions and possible responses but each survey ID is not unique to a client, since many clients may take the same survey. 

what we need is something to group everything together so we know that surveyResponseID has responses a, b, c ,d included. if we were to update would would be able to update reupload a survey with the same surveyResponseID and tie in new responses in case a survey was edited. 

Does that make sense?

**Comment by eric-jahn** [comment]
So per @CTAJavier , survey submissions have state.  "... if you were to do a new survey, it would change the length of time since they were surveyed which would  affect their ranking in a tie".  So it's important to be able to edit an old survey, and not always add a new response to a new survey.

**Comment by eric-jahn** [comment]
APIs updated on the API site [here](https://anypoint.mulesoft.com/apiplatform/apis/#/portals/organizations/1d2d1eb1-46af-4ee8-aa04-bd79ed2764a3/apis/58607/versions/60915).  

See  1) POST /clients/{clientid}/surveys/{surveyid}/responses
2) GET / PUT  / DELETE /clients/{clientid}/surveys/{surveyid}/submissions/{submissionid}

@suryayadavalli , please check in your raml to this repo, and we can close this, since this is just the api documentation issue.

**Comment by suryayadavalli** [comment]
Resolved, deployed in production.
